model:
  package: invictusicap
  filename: ./generated/models_gen.go # https://github.com/99designs/gqlgen/tree/master/plugin/modelgen
client:
  package: invictusicap
  filename: ./generated/client.go # Where should any generated client go?
models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
endpoint:
  url: http://localhost:8080/graphql # Where do you want to send your request?
query:
  - '../db/operations/**/*.graphql' # Where are all the query files located?
